<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="1" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="22297" started-at="2017-05-18T08:13:06Z" finished-at="2017-05-18T08:13:28Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="22297" started-at="2017-05-18T08:13:06Z" finished-at="2017-05-18T08:13:28Z">
      <class name="com.redbus.testCases.Extent2_version2">
        <test-method status="PASS" signature="init1()[pri:0, instance:com.redbus.testCases.Extent2_version2@1c62251]" name="init1" is-config="true" duration-ms="13068" started-at="2017-05-18T13:43:06Z" finished-at="2017-05-18T13:43:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init1 -->
        <test-method status="PASS" signature="init_extent_v02()[pri:0, instance:com.redbus.testCases.Extent2_version2@1c62251]" name="init_extent_v02" duration-ms="9184" started-at="2017-05-18T13:43:19Z" finished-at="2017-05-18T13:43:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init_extent_v02 -->
        <test-method status="FAIL" signature="after_test_compiled(org.testng.ITestResult)[pri:0, instance:com.redbus.testCases.Extent2_version2@1c62251]" name="after_test_compiled" is-config="true" duration-ms="0" started-at="2017-05-18T13:43:28Z" finished-at="2017-05-18T13:43:28Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[wrong number of arguments]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.TestRunner.afterRun(TestRunner.java:983)
	at org.testng.TestRunner.run(TestRunner.java:614)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- after_test_compiled -->
      </class> <!-- com.redbus.testCases.Extent2_version2 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
